BEGIN;

-- Drops
DROP TABLE IF EXISTS "category", "quantity", "ingredient", "media", "user";
DROP DOMAIN IF EXISTS "email";

-- Regex pour le contrôle des emails utilisateurs 
CREATE DOMAIN IF EXISTS "email" AS text
CHECK(
    value ~ '(?:[a-z0-9!#$%&''*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&''*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])'
);

-- Types enum
CREATE TYPE user_role AS ENUM ('admin', 'member');
CREATE TYPE difficulty_level AS ENUM ('Facile', 'Moyen', 'Difficile');
CREATE TYPE recipe_cost AS ENUM ('Petit budget', 'Rapport qualité prix', 'Couteux');

-- Tables
CREATE TABLE "user" (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name       TEXT NOT NULL,
  last_name        TEXT NOT NULL,
  password         TEXT NOT NULL,
  email            email UNIQUE NOT NULL,
  role             user_role NOT NULL DEFAULT 'member',
  status           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ
);

CREATE TABLE recipe (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title        TEXT NOT NULL,
  image        TEXT,
  description  TEXT,
  instruction  TEXT NOT NULL,
  duration     TEXT NOT NULL,
  difficulty   difficulty_level NOT NULL,
  cost         recipe_cost NOT NULL,
  user_id      INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
  status       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMPTZ
);


CREATE TABLE category (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name            TEXT NOT NULL,
  recipe_id       INTEGER REFERENCES recipe(id) ON DELETE CASCADE,
  status          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMPTZ

);

CREATE TABLE ingredient (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name             TEXT NOT NULL,
  unity            TEXT NOT NULL,
  status           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ
);

CREATE TABLE media (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title        TEXT NOT NULL,
  type         TEXT NOT NULL,
  description  TEXT,
  label        TEXT,
  recipe_id    INTEGER REFERENCES recipe(id) ON DELETE CASCADE,
  status       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMPTZ
);

CREATE TABLE quantity (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  recipe_id       INTEGER NOT NULL REFERENCES recipe(id) ON DELETE CASCADE,
  ingredient_id   INTEGER NOT NULL REFERENCES ingredient(id) ON DELETE CASCADE,
  quantity        INTEGER NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMPTZ
);

COMMIT;


