BEGIN;

// Regex pour le contrôle des emails utilisateurs

// Tables
DROP TABLE IF EXISTS "category", "quantity", "ingredient", "media", "user";

CREATE TABLE category (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name            TEXT,
  recipe_id       TEXT NOT NULL
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ

);

CREATE TABLE quantity (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  recipe_id       INTEGER,
  quantity        INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ
);

CREATE TABLE ingredient (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name             TEXT,
  unity            TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ
);

CREATE TABLE media (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title        TEXT,
  type         TEXT,
  description  TEXT,
  label        TEXT,
  recipe_id    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ
);

CREATE TABLE recipe (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title        TEXT NOT NULL,
  image        TEXT,
  description  TEXT,
  instruction  TEXT NOT NULL,
  duration     TEXT,
  difficulty   TEXT,
  cost         TEXT,
  status       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ
);

CREATE TABLE user (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name       TEXT,
  last_name        TEXT,
  password         TEXT,
  email            TEXT,
  role             TEXT,
  status           TEXT,
  recipe_id        TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ
);

ALTER TABLE CATEGORIE ADD FOREIGN KEY (code_recette) REFERENCES RECETTE (code_recette);

ALTER TABLE COMPOSER ADD FOREIGN KEY (code_recette) REFERENCES RECETTE (code_recette);
ALTER TABLE COMPOSER ADD FOREIGN KEY (code_ingredient) REFERENCES INGREDIENT (code_ingredient);

ALTER TABLE MEDIA ADD FOREIGN KEY (code_recette) REFERENCES RECETTE (code_recette);

ALTER TABLE UTILISATEUR ADD FOREIGN KEY (code_recette) REFERENCES RECETTE (code_recette);


COMMIT;
--- --------------------------------------------------------------

CREATE TABLE USER (
  user_id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  last_name      TEXT NOT NULL,
  first_name     TEXT NOT NULL,
  password       TEXT NOT NULL,
  email          TEXT UNIQUE NOT NULL,
  role           user_role NOT NULL,
  status         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE RECIPE (
  recipe_id      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title          TEXT NOT NULL,
  image          TEXT,
  description    TEXT,
  instructions   TEXT NOT NULL,
  duration       TEXT NOT NULL,
  difficulty     difficulty_level,
  cost           recipe_cost,
  status         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORY (
  category_id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name           TEXT NOT NULL
);

CREATE TABLE INGREDIENT (
  ingredient_id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name           TEXT NOT NULL,
  unit           TEXT NOT NULL
);

CREATE TABLE MEDIA (
  media_id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title          TEXT NOT NULL,
  type           TEXT NOT NULL,  -- e.g. 'image', 'video'
  description    TEXT,
  genre          TEXT
);

-- Junction tables

CREATE TABLE COMPOSE (
  recipe_id      INTEGER NOT NULL,
  ingredient_id  INTEGER NOT NULL,
  quantity       INTEGER NOT NULL,
  PRIMARY KEY (recipe_id, ingredient_id),
  FOREIGN KEY (recipe_id) REFERENCES RECIPE (recipe_id) ON DELETE CASCADE,
  FOREIGN KEY (ingredient_id) REFERENCES INGREDIENT (ingredient_id) ON DELETE CASCADE
);

CREATE TABLE CREATE_LINK (
  recipe_id      INTEGER NOT NULL,
  user_id        INTEGER NOT NULL,
  PRIMARY KEY (recipe_id, user_id),
  FOREIGN KEY (recipe_id) REFERENCES RECIPE (recipe_id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES USER (user_id) ON DELETE CASCADE
);

CREATE TABLE LINK (
  recipe_id      INTEGER NOT NULL,
  category_id    INTEGER NOT NULL,
  PRIMARY KEY (recipe_id, category_id),
  FOREIGN KEY (recipe_id) REFERENCES RECIPE (recipe_id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES CATEGORY (category_id) ON DELETE CASCADE
);

CREATE TABLE ORIGIN (
  recipe_id      INTEGER NOT NULL,
  media_id       INTEGER NOT NULL,
  PRIMARY KEY (recipe_id, media_id),
  FOREIGN KEY (recipe_id) REFERENCES RECIPE (recipe_id) ON DELETE CASCADE,
  FOREIGN KEY (media_id) REFERENCES MEDIA (media_id) ON DELETE CASCADE
);

COMMIT;