services:
  - type: web
    name: cine-delices-api
    env: docker
    plan: free
    autoDeploy: true

    healthCheckPath: "/"

    # dockerfilePath: ./Dockerfile   # décommente si ton Dockerfile n'est pas à la racine

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BASE_URL
        sync: false
      - key: PG_URL
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_DB
        sync: false
      - key: PG_PWD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_TYPE
        sync: false
      - key: ACCESS_TOKEN_ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRES_IN_MS
        sync: false
      - key: ACCESS_TOKEN_AUDIENCE
        sync: false
      - key: ACCESS_TOKEN_ISSUER
        sync: false
      - key: SESSION_SECRET
        sync: false
